### ISSUE TITLE
How it works- Dokumentation

### ISSUE THREAD

**Issue by Consti10** [HD-Fpv/Open.HD_AndroidApp#2]
Looks like the settings app has 
a) its own view for every option
b) they each link to the appropriate string in WFBCDataModel
c) modifying them sets a 'dirty bit' which initiates a transfer to the RPI.

The transfer is over UDP and contains an id-value tuple.

These value tuples are then written in the settings.sh file on the ground pi.
And somehow also transmitted to the air pi ?
--> I will post these short thoughts also on the GitHub page, together with my ideas for improvements.

Who can correct / confirm my short description

**Comment by user1321** [comment]
yes, that's correct.
There are two types of UDP messages:
1.UDP packets that are send from phone to Ground RPi.
2. UDP packets that are send inside Ground RPi (Python process to UDP Tx program). That program send them via WiFi link after.
I have a diagram how that all works...
I will try to share it.

P.s.
Tx, rx - its https://github.com/user1321/cameracontrol/tree/master/IPCamera/svpcom_wifibroadcast
Image not at 100 actual now, minor changes to tx,rx params, but in general idea same.

**Comment by user1321** [comment]
![2](https://user-images.githubusercontent.com/33780612/53106048-ebaefd80-353a-11e9-8759-b55f516be8b1.png)

**Comment by Consti10** [comment]
Thanks Vitaly,

For now I only have 1 question: The confirmation of changes on the air pi, does it get processed by RemoteSettings.py also ? or is it just forwarded to the app ?

**Comment by user1321** [comment]
Ground python script do not process any response from Air. ( take a look at picture) 
Instead, response from Air unit forwarded directly to phone via rx -> socat.
Inside phone application there is a variable with name something like AirACK... (same as GroundACK)
In case if both AirACK and GroundACK will be received by phone application, requested (changed) field will turn to green color.
At this moment phone don`t automatically resend request`s in case if it lost.
In near future I will rewrite that. I will try to implement some kind of "guaranteed message delivery".
At this moment I suggest - don`t wast time at this code.
I will send message to telegram messenger when it will be ready. ( less than a month. ) At this moment I wish to fix other minor problems.
