### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Consti10** [HD-Fpv/Open.HD_AndroidApp#3]
Dealing with so many settings is not easy - but I can spot a common pattern that can be definitely improved. Each settings value is basically a key-value-tuple with an dirty bit.

Instead of following the name scheme (example)
public String Copter;
 public String Copterb;
 public int CopterIsChanged = 0;
 public int CopterAirAck = 0;
 public int CopterGroundAck = 0;

just create a class 
class MySetting{
public String key,value;
public int changed,ackAir,ackGround;
}
and then for each setting

MySetting Copter;
MySetting Imperial;

This generalization will decrease the amount of code immensely.

**Comment by zipray** [comment]
‎ @Consti10 
     Very good idea,in order to save resources, when only use telemetry OSD display, can I close the configuration services in air and ground PI?All it takes is a one-way close the services,just restart to enable configuration services.
