### ISSUE TITLE
Changing fps

### ISSUE THREAD

**Issue by Consti10** [HD-Fpv/Open.HD_AndroidApp#4]
Hello,
I just tried to change the camera FPS settings using the Open.HD app (no modifications on the source code
yet).
I modified the FPS value to 20 , then clicked SAVE.
The app showed something like 'saved to ground and air'.
The I reopened my FPV-VR app , but fps is still ~45.

Now I have the SD card of the ground pi open, and there are two files:
openhd-settings-1.txt and openhd-settings-2.txt.

settings-1 shows 20, settings-2 shows 48 fps. 

Question: why are there 2 settings files ?
My assumption: the settings-2 file is never modified and a template for creating settings1

Next, I will try restarting the air pi myself and see what happens

**Comment by Consti10** [comment]
Opened the sd card of the air pi - content of settings-1 fps=20
settings-2 fps_48.

Then restarted air pi and voila, changing fps worked !

I will now modify the Open.HD app to include the described imrpovements ( and more - The code leaves a lot open for generalization ) but leave the Open.HD files untouched.

I'l keep you updated and publish the modifed code on github.

**Comment by pilotnbr1** [comment]
just a side note with fps. You really dont get the exact fps you enter when you are below 60. It forces you to specific fps scripts. Maybe in the app that field can be a drop down with preset values..

function set_video_player_based_fps {
	# mmormota's stutter-free hello_video.bin: "hello_video.bin.30-mm" (for 30fps) or "hello_video.bin.48-mm" (for 48 and 59.9fps)
	# befinitiv's hello_video.bin: "hello_video.bin.240-befi" (for any fps, use this for higher than 59.9fps)

	if [ "$FPS" == "59.9" ]; then
		DISPLAY_PROGRAM=/opt/vc/src/hello_pi/hello_video/hello_video.bin.48-mm
	else
		if [ "$FPS" -eq 30 ]; then
			DISPLAY_PROGRAM=/opt/vc/src/hello_pi/hello_video/hello_video.bin.30-mm
		fi
		if [ "$FPS" -lt 60 ]; then
			DISPLAY_PROGRAM=/opt/vc/src/hello_pi/hello_video/hello_video.bin.48-mm
		fi
		if [ "$FPS" -gt 60 ]; then
			DISPLAY_PROGRAM=/opt/vc/src/hello_pi/hello_video/hello_video.bin.240-befi
		fi
	fi
}

**Comment by htcohio** [comment]
Can this issue be closed?

Also, Consti, there are 2 config.txt files by default, This was designed to have gpio (Pins 39&40) act as a "Default" function because in the event multiple uav/drones with different settings are in the field, openhd-settings.txt-2 can be loaded by dipswitch or "button" held during boot process and "2" profile would remain the same on all drones...

As such, the Open.HD App only makes changes to Profile "1" even if Profile "2" (default) was loaded it maintains the 2-way sync of air/ground sides...

**Comment by Consti10** [comment]
Hello,

@pilotnbr1 :  Like already implemented by vitaliy, I will keep the 2 input modes for changing values on the android side:
1) EditText for values that don't need to be validated
2) Dropdown Edit text (or however the view is called :) ) for checked values

@htcohio 
Yes it can. Especially after your explanation about the -1 and -2 files.

**Comment by pilotnbr1** [comment]
So settings file is an interesting animal at the moment. 

The potential problem as I understand is the app always tries to read and write from openhd-settings-1.txt
This does not allow the use of gpio selectable settings files.

The flow is confusing and starts with the pins being read in /wifibroadcast_misc/gpio-config.py
Presently viewable in the builder at stage 4 /files/overlay/root


The whole flow is something like-

etc/Systemd/system has a oneshot service named wbcconfig.service

wbcconfig.service calls /root/wifibroadcast_misc/wbcconfig.sh

wbcconfig in turn references /root/wifibroadcast_misc/gpio-config.py

in gpio-config.py it "import RPi.GPIO" which is managed by raspbian and monitors gpio pins on boot
